name: Build and Test with Atlassian Maven
on: [push, pull_request]

jobs:
   build-and-test:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Set up Java
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       # Per https://developer.atlassian.com/server/framework/atlassian-sdk/install-the-atlassian-sdk-on-a-linux-or-mac-system/
       - name: Install Atlassian SDK
         run: |
           sudo sh -c 'echo "deb https://packages.atlassian.com/debian/atlassian-sdk-deb/ stable contrib" >>/etc/apt/sources.list'
           wget https://packages.atlassian.com/api/gpg/key/public
           sudo apt-key add public
           sudo apt-get update
           sudo apt-get install -y atlassian-plugin-sdk
       - name: Build and test with Maven
         run: atlas-mvn clean package
       - name: Upload jar artifact
         uses: actions/upload-artifact@v2
         with:
           name: my-artifact
           path: duo_seraph_filter/target/duo-filter-*
